master: 
  epochs: 1201
  lr: 4e-4
  lr2: 1e-4
  bsize: 256
  n_flow: 3
  nh: 32
  lr_milestone: [200, 600]
  lr_gamma: 0.1
  lr2_milestone: [800]
  l2_gamma: 3.0

trial1: 
  epochs: 3
  lr: 1e-3
  lr2: 1e-4
  bsize: 256
  n_flow: 3
  nh: 32
  lr_milestone: [200, 600]
  lr_gamma: 0.1
  lr2_milestone: [800]
  l2_gamma: 3.0